all:
	g++ -o testBinaryTree.exe testBinaryTree.cpp -lgtest -lgtest_main -pthread
	g++ -o testIterator.exe testIterator.cpp -lgtest -lgtest_main -pthread
tests:
	./testBinaryTree.exe
	./testIterator.exe